version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker.io/stephenlautier/netcore-docker-ci:5.0.0-net6
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
    steps:
      - run:
          name: Print environment versions
          command: |
            NPM_V=$(npm -v)
            echo npm version':' $NPM_V
            DOTNET_CLI_V=$(dotnet --version)
            echo dotnet cli version':' $DOTNET_CLI_V
      - checkout
      - run:
          name: dotnet restore
          command: dotnet restore
      - run:
          name: dotnet build
          command: dotnet build -c Release
      - run:
          name: test
          command: npm test
      - run:
          name: Check if branch is publishable
          command: |
            if ! ([ $CIRCLE_BRANCH = "master" ] || [[ "$CIRCLE_BRANCH" =~ ^(([0-9]+|\.)+x)$ ]]); then
              echo "Non-publishable branch; finishing build..."
              circleci step halt
            fi
      - deploy:
          name: Publish NuGet
          command: |
            export SKETCH7_NUGET_API_KEY=$API_KEY

            npm run publish:dev
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: nuget